// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwSJ0Q_SRx7Ugqst4WaRbW3e0ls0quYq8',
    appId: '1:640798914834:web:b894c6394a027de08fdbcb',
    messagingSenderId: '640798914834',
    projectId: 'nssmain-bd6f7',
    authDomain: 'nssmain-bd6f7.firebaseapp.com',
    storageBucket: 'nssmain-bd6f7.firebasestorage.app',
    measurementId: 'G-GYX8FENX1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mv5dAndMeECSglJaOCxqV-Szy5ZmFX4',
    appId: '1:640798914834:android:53690cd2cc9f12558fdbcb',
    messagingSenderId: '640798914834',
    projectId: 'nssmain-bd6f7',
    storageBucket: 'nssmain-bd6f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsD_SK8lPmPaYoGSbUu_72dWG-lR1bjI',
    appId: '1:640798914834:ios:b62c5f72e286e7468fdbcb',
    messagingSenderId: '640798914834',
    projectId: 'nssmain-bd6f7',
    storageBucket: 'nssmain-bd6f7.firebasestorage.app',
    iosBundleId: 'com.example.nssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB21V2To6Sye8TDFYf0k4rNYOpCSB8WR0k',
    appId: '1:902688224431:ios:382ca53ab9fa76e6fe105a',
    messagingSenderId: '902688224431',
    projectId: 'nss1-31a35',
    storageBucket: 'nss1-31a35.firebasestorage.app',
    iosBundleId: 'com.example.nssApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9YMawDUrokemAteXw6N5sepxagXfiFuA',
    appId: '1:902688224431:web:06ddac2e7a3753c9fe105a',
    messagingSenderId: '902688224431',
    projectId: 'nss1-31a35',
    authDomain: 'nss1-31a35.firebaseapp.com',
    storageBucket: 'nss1-31a35.firebasestorage.app',
    measurementId: 'G-LT6WNDNXVT',
  );
}